namespace Feliz.RadixUI.Interface.NoInherit
// AUTOGENERATED FILE - these files do not inherit feliz properties at base
open Feliz
open Fable.Core
open Fable.Core.JsInterop
open Feliz.Shadcn.Interop
open Browser.Types


/// Contains the content to announce.
[<RequireQualifiedAccess>]
module [<Erase>] announceRoot =
    type [<Erase>] aria-atomic<'Property> =
        static member inline boolean : 'Property = Interop.mkProperty "aria-atomic" "boolean"

    type [<Erase>] aria-relevant<'Property> =
        static member inline additions : 'Property = Interop.mkProperty "aria-relevant" "additions"
        static member inline removals : 'Property = Interop.mkProperty "aria-relevant" "removals"
        static member inline text : 'Property = Interop.mkProperty "aria-relevant" "text"

    type [<Erase>] role<'Property> =
        static member inline status : 'Property = Interop.mkProperty "role" "status"
        static member inline alert : 'Property = Interop.mkProperty "role" "alert"
        static member inline log : 'Property = Interop.mkProperty "role" "log"
        static member inline none : 'Property = Interop.mkProperty "role" "none"

    type [<Erase>] type'<'Property> =
        static member inline polite : 'Property = Interop.mkProperty "type" "polite"
        static member inline assertive : 'Property = Interop.mkProperty "type" "assertive"
        static member inline off : 'Property = Interop.mkProperty "type" "off"

/// Announces messages to screen readers.
[<RequireQualifiedAccess>]
module [<Erase>] Announce =
    /// Contains the content to announce.
    type [<Erase>] root<'Property> =
        /// Change the default rendered element for the one passed as a child, merging their props and behavior.
        ///  
        ///  Read our Composition guide for more details.
        static member inline asChild ( value : bool ) : 'Property = Interop.mkProperty "asChild" value
        /// Mirrors the aria-relevant DOM attribute for live regions. It is an optional attribute used to describe what types of changes have occurred to the region, and which changes are relevant and should be announced. Any change that is not relevant acts in the same manner it would if the aria-live attribute were set to off.
        ///  
        ///  Unfortunately, aria-relevant doesn't behave as expected across all device/screen reader combinations. It's important to test its implementation before relying on it to work for your users. The attribute is omitted by default.
        static member inline regionIdentifier ( value : string ) : 'Property = Interop.mkProperty "regionIdentifier" value
