namespace Feliz.RadixUI.Interface.NoInherit
// AUTOGENERATED FILE - these files do not inherit feliz properties at base
open Feliz
open Fable.Core
open Fable.Core.JsInterop
open Feliz.Shadcn.Interop
open Browser.Types


/// Displays content within a desired ratio.
[<RequireQualifiedAccess>]
module [<Erase>] AspectRatio =
    /// Contains the content you want to constrain to a given ratio.
    type [<Erase>] root<'Property> =
        /// Change the default rendered element for the one passed as a child, merging their props and behavior.
        ///  
        ///  Read our Composition guide for more details.
        static member inline asChild ( value : bool ) : 'Property = Interop.mkProperty "asChild" value
        /// The desired ratio
        static member inline ratio ( value : int ) : 'Property = Interop.mkProperty "ratio" value
